name: dbgap-reporter 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.8
  - jupyterlab=3
  - jupyter-offlinenotebook
  - pandas=1.5.2
  - ipywidgets=7.6.5
  - selenium=4.7.2
  - webdriver-manager=3.8.5
  - black
  - pip
  - pip:
    - chromedriver-binary-auto
